import { mutation } from "./_generated/server";

const ACTIVITIES = [
  {
    title: "Spacer po parku",
    description: "Odpręż się na świeżym powietrzu wśród zieleni.",
    category: "outdoor",
    durationMin: 45,
    cost: "free" as const,
    energy: "low" as const,
    social: "solo" as const,
    location: "outdoor" as const,
    weather: "sunny" as const,
    tags: ["natura", "relaks", "ruch"],
  },
  {
    title: "Maraton filmowy w domu",
    description: "Ulubiona trylogia, koc i popcorn.",
    category: "relax",
    durationMin: 240,
    cost: "low" as const,
    energy: "low" as const,
    social: "duo" as const,
    location: "indoor" as const,
    weather: "rainy" as const,
    tags: ["film", "relaks", "kanapa"],
  },
  {
    title: "Bieg interwałowy",
    description: "Krótki, intensywny trening w terenie.",
    category: "active",
    durationMin: 30,
    cost: "free" as const,
    energy: "high" as const,
    social: "solo" as const,
    location: "outdoor" as const,
    weather: "any" as const,
    tags: ["sport", "kondycja", "ruch"],
  },
  {
    title: "Wieczór planszówkowy",
    description: "Zaproś znajomych na kilka gier planszowych.",
    category: "social",
    durationMin: 180,
    cost: "low" as const,
    energy: "medium" as const,
    social: "group" as const,
    location: "indoor" as const,
    weather: "any" as const,
    tags: ["gry", "znajomi", "śmiech"],
  },
  {
    title: "Warsztaty ceramiki",
    description: "Ulep swój kubek od zera.",
    category: "creative",
    durationMin: 120,
    cost: "medium" as const,
    energy: "medium" as const,
    social: "duo" as const,
    location: "indoor" as const,
    weather: "any" as const,
    tags: ["kreatywność", "rękodzieło", "nowość"],
  },
  {
    title: "Wycieczka rowerowa",
    description: "Zaplanuj trasę i ruszaj w teren.",
    category: "active",
    durationMin: 150,
    cost: "free" as const,
    energy: "high" as const,
    social: "duo" as const,
    location: "outdoor" as const,
    weather: "sunny" as const,
    tags: ["sport", "natura", "przygoda"],
  },
  {
    title: "Wizyta w muzeum",
    description: "Odkryj nową wystawę w lokalnym muzeum.",
    category: "culture",
    durationMin: 90,
    cost: "low" as const,
    energy: "low" as const,
    social: "solo" as const,
    location: "indoor" as const,
    weather: "rainy" as const,
    tags: ["kultura", "wiedza", "sztuka"],
  },
  {
    title: "Gotowanie nowego przepisu",
    description: "Wybierz kuchnię, której nigdy nie próbowałeś.",
    category: "food",
    durationMin: 75,
    cost: "medium" as const,
    energy: "medium" as const,
    social: "duo" as const,
    location: "indoor" as const,
    weather: "any" as const,
    tags: ["kuchnia", "kreatywność", "smak"],
  },
  {
    title: "Medytacja poranna",
    description: "10 minut uważności na początek dnia.",
    category: "relax",
    durationMin: 10,
    cost: "free" as const,
    energy: "low" as const,
    social: "solo" as const,
    location: "any" as const,
    weather: "any" as const,
    tags: ["mindfulness", "spokój", "rutyna"],
  },
  {
    title: "Koncert na żywo",
    description: "Sprawdź lokalną scenę i kup bilet.",
    category: "culture",
    durationMin: 150,
    cost: "high" as const,
    energy: "medium" as const,
    social: "group" as const,
    location: "indoor" as const,
    weather: "any" as const,
    tags: ["muzyka", "wieczór", "wyjście"],
  },
  {
    title: "Piknik w parku",
    description: "Kosz, koc i dobre towarzystwo.",
    category: "social",
    durationMin: 120,
    cost: "low" as const,
    energy: "low" as const,
    social: "group" as const,
    location: "outdoor" as const,
    weather: "sunny" as const,
    tags: ["jedzenie", "natura", "znajomi"],
  },
  {
    title: "Joga w domu",
    description: "Rozciągnij się i odetchnij po pracy.",
    category: "relax",
    durationMin: 40,
    cost: "free" as const,
    energy: "medium" as const,
    social: "solo" as const,
    location: "indoor" as const,
    weather: "any" as const,
    tags: ["ruch", "relaks", "zdrowie"],
  },
  {
    title: "Wieczór z książką",
    description: "Wróć do zakurzonej powieści na półce.",
    category: "relax",
    durationMin: 90,
    cost: "free" as const,
    energy: "low" as const,
    social: "solo" as const,
    location: "indoor" as const,
    weather: "rainy" as const,
    tags: ["książka", "spokój", "wieczór"],
  },
  {
    title: "Wspinaczka na ściance",
    description: "Sprawdź się na kolorowych chwytach.",
    category: "active",
    durationMin: 120,
    cost: "medium" as const,
    energy: "high" as const,
    social: "duo" as const,
    location: "indoor" as const,
    weather: "any" as const,
    tags: ["sport", "wyzwanie", "adrenalina"],
  },
  {
    title: "Kawa z przyjacielem",
    description: "Umów się i nadrób zaległości.",
    category: "social",
    durationMin: 60,
    cost: "low" as const,
    energy: "low" as const,
    social: "duo" as const,
    location: "indoor" as const,
    weather: "any" as const,
    tags: ["rozmowa", "znajomi", "kawa"],
  },
  {
    title: "Fotospacer po mieście",
    description: "Złap aparat i poszukaj kadrów.",
    category: "creative",
    durationMin: 90,
    cost: "free" as const,
    energy: "medium" as const,
    social: "solo" as const,
    location: "outdoor" as const,
    weather: "any" as const,
    tags: ["fotografia", "miasto", "kreatywność"],
  },
  {
    title: "Sesja pisania dziennika",
    description: "Zapisz wrażenia i plany na papierze.",
    category: "creative",
    durationMin: 20,
    cost: "free" as const,
    energy: "low" as const,
    social: "solo" as const,
    location: "any" as const,
    weather: "any" as const,
    tags: ["refleksja", "pisanie", "rutyna"],
  },
  {
    title: "Wieczór karaoke",
    description: "Wyśpiewaj się z ekipą.",
    category: "social",
    durationMin: 180,
    cost: "medium" as const,
    energy: "high" as const,
    social: "group" as const,
    location: "indoor" as const,
    weather: "any" as const,
    tags: ["muzyka", "śmiech", "wyjście"],
  },
];

export const seedActivities = mutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query("activities").collect();
    for (const row of existing) {
      await ctx.db.delete(row._id);
    }
    for (const activity of ACTIVITIES) {
      await ctx.db.insert("activities", activity);
    }
    return { inserted: ACTIVITIES.length };
  },
});
